import type { Theme } from './types.js';

export const draculaTheme: Theme = {
  id: 'dracula',
  name: 'Dracula',
  description: '暗紫色赛博吸血鬼美学，粉青撞色的视觉冲击',
  codeTheme: 'dracula',
  styles: {
    container: 'max-width: 100%; margin: 0 auto; padding: 14px 14px 28px 14px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #f8f8f2 !important; background-color: #282a36 !important; word-wrap: break-word;',
    h1: 'font-size: 32px; font-weight: 700; color: #bd93f9 !important; line-height: 1.3 !important; margin: 0 0 16px; letter-spacing: -0.015em;',
    h2: 'font-size: 26px; font-weight: 600; color: #ff79c6 !important; line-height: 1.35 !important; margin: 24px 0 12px;',
    h3: 'font-size: 21px; font-weight: 600; color: #8be9fd !important; line-height: 1.4 !important; margin: 20px 0 10px;',
    h4: 'font-size: 18px; font-weight: 600; color: #50fa7b !important; line-height: 1.4 !important; margin: 16px 0 8px;',
    p: 'margin: 12px 0 !important; line-height: 1.7 !important; color: #f8f8f2 !important;',
    strong: 'font-weight: 700; color: #ffb86c !important;',
    em: 'font-style: italic; color: #8be9fd !important;',
    a: 'color: #8be9fd !important; text-decoration: none; border-bottom: 1px solid #8be9fd; padding-bottom: 1px;',
    ul: 'margin: 12px 0; padding-left: 28px;',
    ol: 'margin: 12px 0; padding-left: 28px;',
    li: 'margin: 8px 0; line-height: 1.7 !important; color: #f8f8f2 !important;',
    blockquote: 'margin: 16px 0; padding: 16px 20px; background-color: #44475a !important; border-left: 4px solid #bd93f9; color: #f8f8f2 !important; border-radius: 4px;',
    code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #44475a !important; color: #50fa7b !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
    pre: 'margin: 16px 0; padding: 20px; background-color: #44475a !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
    table: 'width: 100%; margin: 16px 0; border-collapse: collapse; font-size: 15px;',
    th: 'background-color: #44475a !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #bd93f9 !important; border: 1px solid #6272a4;',
    td: 'padding: 12px 16px; border: 1px solid #6272a4; color: #f8f8f2 !important;',
    tr_even: 'background-color: #44475a;',
    hr: 'margin: 24px auto; border: none; height: 1px; background-color: #6272a4 !important; width: 100%;',
    img: 'max-width: 100%; height: auto; display: block; margin: 12px auto; border-radius: 4px;',
  },
};
